name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign to One Project
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/vImpact/projects/2/views/1'
        column_name: 'Autofill'
